# Generated by Django 5.2.9 on 2026-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_can_teach_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_teach',
            field=models.BooleanField(default=False, help_text='Whether this account is allowed to edit syllabus and related course content as a non-admin/editor role.', verbose_name='Can edit/manage syllabus content'),
        ),
    ]
