# Generated by Django 5.2.9 on 2026-01-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ai_check', 'На проверке ИИ'), ('correction', 'На доработке'), ('review_dean', 'Согласование: Декан'), ('review_umu', 'Согласование: УМУ'), ('approved', 'Утвержден'), ('rejected', 'Отклонено (Архив)')], default='draft', max_length=32)),
                ('total_weeks', models.PositiveIntegerField(default=15)),
                ('main_language', models.CharField(choices=[('ru', 'Русский'), ('kz', 'Казахский'), ('en', 'English')], default='ru', max_length=5)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='syllabi_pdfs/')),
                ('is_shared', models.BooleanField(default=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('ai_feedback', models.TextField(blank=True, help_text='Замечания от ИИ проверки')),
                ('credits_ects', models.CharField(blank=True, max_length=20)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('self_study_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('delivery_format', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('instructor_name', models.CharField(blank=True, max_length=255)),
                ('instructor_contacts', models.TextField(blank=True)),
                ('class_schedule', models.TextField(blank=True)),
                ('course_description', models.TextField(blank=True)),
                ('course_goal', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('teaching_methods', models.TextField(blank=True)),
                ('teaching_philosophy', models.TextField(blank=True)),
                ('course_policy', models.TextField(blank=True)),
                ('academic_integrity_policy', models.TextField(blank=True)),
                ('inclusive_policy', models.TextField(blank=True)),
                ('assessment_policy', models.TextField(blank=True)),
                ('grading_scale', models.TextField(blank=True)),
                ('appendix', models.TextField(blank=True)),
                ('main_literature', models.TextField(blank=True)),
                ('additional_literature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='catalog.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='syllabi.syllabus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('is_included', models.BooleanField(default=True)),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('custom_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('week_label', models.CharField(blank=True, max_length=20)),
                ('tasks', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('literature_notes', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_topics', to='syllabi.syllabus')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.topic')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
