# Generated by Django 5.2.9 on 2026-02-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('syllabi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Силлабус', 'verbose_name_plural': 'Силлабусы'},
        ),
        migrations.AlterModelOptions(
            name='syllabusrevision',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ревизия', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AlterModelOptions(
            name='syllabustopic',
            options={'ordering': ['week_number'], 'verbose_name': 'Тема силлабуса', 'verbose_name_plural': 'Темы силлабуса'},
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='academic_integrity_policy',
            field=models.TextField(blank=True, verbose_name='Академическая честность'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='additional_literature',
            field=models.TextField(blank=True, verbose_name='Дополнительная литература'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Замечания от автоматической проверки', verbose_name='Отчет ИИ'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='appendix',
            field=models.TextField(blank=True, verbose_name='Приложения'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='assessment_policy',
            field=models.TextField(blank=True, verbose_name='Политика оценивания'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='class_schedule',
            field=models.TextField(blank=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='contact_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Аудиторные часы'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='catalog.course', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_description',
            field=models.TextField(blank=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_goal',
            field=models.TextField(blank=True, verbose_name='Цель курса'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course_policy',
            field=models.TextField(blank=True, verbose_name='Политика курса'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='credits_ects',
            field=models.CharField(blank=True, max_length=20, verbose_name='Кредиты (ECTS)'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='delivery_format',
            field=models.CharField(blank=True, max_length=100, verbose_name='Формат обучения'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='grading_scale',
            field=models.TextField(blank=True, verbose_name='Шкала оценки'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='inclusive_policy',
            field=models.TextField(blank=True, verbose_name='Инклюзивная политика'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instructor_contacts',
            field=models.TextField(blank=True, verbose_name='Контакты преподавателя'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Доступен другим?'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='learning_outcomes',
            field=models.TextField(blank=True, verbose_name='Ожидаемые результаты'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='main_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kz', 'Казахский'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык силлабуса'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='main_literature',
            field=models.TextField(blank=True, verbose_name='Основная литература'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabi_pdfs/', verbose_name='Файл силлабуса'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='Пререквизиты'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Образовательная программа'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='self_study_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='СРО/СРОП'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='semester',
            field=models.CharField(max_length=50, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ai_check', 'На проверке ИИ'), ('correction', 'На доработке'), ('review_dean', 'Согласование: Декан'), ('review_umu', 'Согласование: УМУ'), ('approved', 'Утвержден'), ('rejected', 'Отклонено (Архив)')], default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='teaching_methods',
            field=models.TextField(blank=True, verbose_name='Методы обучения'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='teaching_philosophy',
            field=models.TextField(blank=True, verbose_name='Философия преподавания'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего часов'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='total_weeks',
            field=models.PositiveIntegerField(default=15, verbose_name='Количество недель'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='version_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='assessment',
            field=models.TextField(blank=True, verbose_name='Оценивание (тема)'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='custom_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Часы (кастом)'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='custom_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кастомное название'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='is_included',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='learning_outcomes',
            field=models.TextField(blank=True, verbose_name='Результаты (тема)'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='literature_notes',
            field=models.TextField(blank=True, verbose_name='Литература (тема)'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='tasks',
            field=models.TextField(blank=True, verbose_name='Задания'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.topic', verbose_name='Тема из каталога'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='week_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='Метка недели'),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='week_number',
            field=models.PositiveIntegerField(verbose_name='Номер недели'),
        ),
    ]
