# Generated by Django 5.2.9 on 2026-05-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0004_syllabus_ai_claim_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='school',
            field=models.CharField(blank=True, max_length=255, verbose_name='Школа согласования'),
        ),
    ]
