# Generated by Django 5.2.9 on 2026-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0005_syllabus_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ai_check', 'На проверке ИИ'), ('correction', 'На доработке'), ('ready_dean', 'Готов к отправке декану'), ('review_dean', 'Согласование: Декан'), ('review_umu', 'Согласование: УМУ'), ('approved', 'Утвержден'), ('rejected', 'Отклонено (Архив)')], default='draft', max_length=32, verbose_name='Статус'),
        ),
    ]
